# Generated by Django 5.1 on 2024-08-22 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nick', models.CharField(max_length=30)),
                ('avatar', models.ImageField(default='default_avatar.jpg', upload_to='')),
                ('friends_confirmed', models.ManyToManyField(related_name='friend_conf', to='appong.userprofile')),
                ('friends_pending', models.ManyToManyField(related_name='friend_pend', to='appong.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourn_start_time', models.DateTimeField()),
                ('tourn_name', models.CharField(max_length=30)),
                ('tourn_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appong.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(default=0)),
                ('match_start_time', models.DateTimeField()),
                ('player1_hit_nb', models.IntegerField(default=0)),
                ('player2_hit_nb', models.IntegerField(default=0)),
                ('player1_perfect_hit_nb', models.IntegerField(default=0)),
                ('player2_perfect_hit_nb', models.IntegerField(default=0)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('ball_max_speed', models.IntegerField(default=0)),
                ('match_runtime', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='appong.userprofile')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='appong.userprofile')),
            ],
        ),
    ]
