# Generated by Django 5.1 on 2024-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tourn_confirmed',
            field=models.ManyToManyField(blank=True, related_name='tourn_conf', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_pending',
            field=models.ManyToManyField(blank=True, related_name='tourn_pend', to='appong.userprofile'),
        ),
    ]
