# Generated by Django 5.1 on 2024-09-05 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends_pending',
        ),
        migrations.AlterField(
            model_name='match',
            name='ball_max_speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_hit_nb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_perfect_hit_nb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_hit_nb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_perfect_hit_nb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='appong.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_confirmed',
            field=models.ManyToManyField(blank=True, related_name='tourn_conf', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_pending',
            field=models.ManyToManyField(blank=True, related_name='tourn_pend', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Null'), (2, 'Pending'), (3, 'Confirmed')], default=1)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appong.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, through='appong.Friend', to='appong.userprofile'),
        ),
    ]
