# Generated by Django 5.1 on 2024-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0002_remove_userprofile_friends_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tourn_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_nick',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
