# Generated by Django 5.1 on 2024-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0002_alter_match_ball_max_speed_alter_match_match_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends_confirmed',
            field=models.ManyToManyField(blank=True, to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends_pending',
            field=models.ManyToManyField(blank=True, to='appong.userprofile'),
        ),
    ]
