# Generated by Django 5.1 on 2024-09-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0002_remove_userprofile_friends_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='appong.userprofile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='appong.userprofile'),
        ),
    ]
