# Generated by Django 5.1 on 2024-09-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0003_alter_match_ball_max_speed_alter_match_match_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='appong.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_confirmed',
            field=models.ManyToManyField(blank=True, null=True, related_name='tourn_conf', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourn_pending',
            field=models.ManyToManyField(blank=True, null=True, related_name='tourn_pend', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends_confirmed',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_conf', to='appong.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends_pending',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_pend', to='appong.userprofile'),
        ),
    ]
