# Generated by Django 5.1 on 2024-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0003_remove_friend_friend_friend_user1_friend_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', through='appong.Friend', to='appong.userprofile'),
        ),
    ]
