# Generated by Django 5.1 on 2024-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0003_alter_userprofile_friends_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends_remove',
            field=models.ManyToManyField(blank=True, to='appong.userprofile'),
        ),
    ]
