# Generated by Django 5.1 on 2024-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0003_alter_tournament_tourn_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
