# Generated by Django 5.1 on 2024-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0003_alter_userprofile_friends_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_runtime',
            field=models.TimeField(default=0),
        ),
    ]
