# Generated by Django 5.1 on 2024-09-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0004_userprofile_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='online_status',
        ),
    ]
