# Generated by Django 5.1 on 2024-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0004_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, through='appong.Friend', to='appong.userprofile'),
        ),
    ]
