# Generated by Django 5.1 on 2024-08-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0004_alter_match_match_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tourn_confirmed',
            field=models.ManyToManyField(blank=True, related_name='tourn_pend', to='appong.userprofile'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourn_pending',
            field=models.ManyToManyField(blank=True, related_name='tourn_conf', to='appong.userprofile'),
        ),
    ]
