# Generated by Django 5.1 on 2024-09-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0005_remove_userprofile_online_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
