# Generated by Django 5.1 on 2024-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized_images/')),
            ],
        ),
    ]
