# Generated by Django 5.1 on 2024-09-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0007_resizableimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(default='default_avatar.jpg', on_delete=django.db.models.deletion.CASCADE, to='appong.resizableimage'),
        ),
    ]
