# Generated by Django 5.1 on 2024-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0008_add_dashboard_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_start_time',
            field=models.DateTimeField(),
        ),
    ]
