# Generated by Django 5.1 on 2024-09-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizableimage',
            name='original_image',
            field=models.ImageField(default='default_avatar.jpg', upload_to='original_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appong.resizableimage'),
        ),
    ]
