# Generated by Django 5.1 on 2024-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0009_alter_resizableimage_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizableimage',
            name='resized_image',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='resized_images/'),
        ),
    ]
