# Generated by Django 5.1 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0010_alter_resizableimage_resized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='ResizableImage',
        ),
    ]
