# Generated by Django 5.1 on 2024-09-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0011_alter_userprofile_avatar_delete_resizableimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends_pending',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Null'), (2, 'Pending'), (3, 'Confirmed')], default=1)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='appong.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='appong.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, through='appong.Friend', to='appong.userprofile'),
        ),
    ]
