# Generated by Django 5.1 on 2024-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0011_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
