# Generated by Django 5.1 on 2024-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0012_alter_tournament_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
