# Generated by Django 5.1 on 2024-09-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0012_remove_userprofile_friends_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friends',
            new_name='friend',
        ),
    ]
