# Generated by Django 5.1 on 2024-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0012_alter_tournament_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
