# Generated by Django 5.1 on 2024-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0013_userprofile_last_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
