# Generated by Django 5.1 on 2024-09-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0014_alter_friend_user1_alter_friend_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friend',
            new_name='friends',
        ),
    ]
