# Generated by Django 5.1 on 2024-09-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appong', '0015_rename_friend_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
    ]
